// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering;

namespace ThAmCo.Catering.Migrations
{
    [DbContext(typeof(CateringContext))]
    [Migration("20210107115221_seedDataCreate")]
    partial class seedDataCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThAmCo.Catering.Models.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientReference");

                    b.Property<int?>("MenuId");

                    b.Property<int>("NumberOfGuests");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("foodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClientReference = 1,
                            MenuId = 1,
                            NumberOfGuests = 15
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClientReference = 2,
                            MenuId = 2,
                            NumberOfGuests = 12
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<float>("UnitPrice");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Tomato Soup",
                            UnitPrice = 4f
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "French Onion Soup",
                            UnitPrice = 3.5f
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Leak & Onion Soup",
                            UnitPrice = 3.75f
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "White bread bun",
                            UnitPrice = 0.75f
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "Wholemeal bun",
                            UnitPrice = 0.75f
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuName");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "French Classic"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "Chef's Soup"
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Models.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuId");

                    b.Property<int>("FoodItemId");

                    b.HasKey("MenuId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 2
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 1
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 4
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Models.FoodBooking", b =>
                {
                    b.HasOne("ThAmCo.Catering.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ThAmCo.Catering.Models.MenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThAmCo.Catering.Models.Menu", "Menu")
                        .WithMany("MenuFoodItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
